spring:
  application:
    name: payment-transfer
  datasource:
    url: jdbc:mariadb://localhost:3306/bank_db
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-payment-transfer.html
    operations-sorter: method
    tags-sorter: alpha